=== ghosert/VimProject/python/StudyPython/diveintopython-5.4/py/kgp/kgp.dtd
<!ELEMENT grammar (ref)+>
<!ELEMENT ref (p)+>
<!ATTLIST ref id ID #REQUIRED>
<!ELEMENT xref EMPTY>
<!ATTLIST xref id IDREF #REQUIRED>
<!ELEMENT choice (p)+>
<!ELEMENT p (#PCDATA|p|xref|choice)*>
<!ATTLIST p class CDATA #IMPLIED>
<!ATTLIST p chance CDATA #IMPLIED>

=== ghosert/VimProject/python/StudyPython/diveintopython-5.4/py/kgp/test.xml
<?xml version="1.0"?>
<!DOCTYPE grammar PUBLIC "-//diveintopython.org//DTD Kant Generator Pro v1.0//EN" "kgp.dtd">
<grammar>
<ref id="a">
  <p>0</p>
</ref>
<ref id="b">
  <p>1</p>
  <p>1</p>
</ref>
<ref id="c">
  <p chance="100">2</p>
</ref>
<ref id="d">
  <p chance="0">3</p>
</ref>
<ref id="e">
  <p><xref id="a"/></p>
</ref>
<ref id="f">
  <p><xref id="b"/><xref id="a"/></p>
</ref>
<ref id="g">
  <p><choice><p>1</p><p>1</p></choice></p>
</ref>
</grammar>

=== ghosert/VimProject/python/StudyPython/diveintopython-5.4/py/kgp/binary.xml
<?xml version="1.0"?>
<!DOCTYPE grammar PUBLIC "-//diveintopython.org//DTD Kant Generator Pro v1.0//EN" "kgp.dtd">
<grammar>
<ref id="bit">
  <p>0</p>
  <p>1</p>
</ref>
<ref id="byte">
  <p><xref id="bit"/><xref id="bit"/><xref id="bit"/><xref id="bit"/><xref id="bit"/><xref id="bit"/><xref id="bit"/><xref id="bit"/></p>
</ref>
</grammar>
